name: Carbon-Intensity-Tracker-UI Workflow

on:
  push:
    paths:
      - 'carbon-intensity-tracker-ui/**'
      - '.github/workflows/ui-workflow.yaml'
  pull_request:
    paths:
      - 'carbon-intensity-tracker-ui/**'
      - '.github/workflows/ui-workflow.yaml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: carbon-intensity-tracker-ui

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: carbon-intensity-tracker-ui/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('carbon-intensity-tracker-ui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Clean install dependencies
        run: npm ci

      - name: Lint project
        run: npm run lint:ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Run tests with coverage
        run: npm run test:coverage
